apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-trainer
spec:
  selector:
    matchLabels:
      app: pytorch
  replicas: 2
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: training-pv-claim
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: pytorch
        image: alex1005/disttrainer:pytorch-1
        env:
        - name: TRAINER_PORT
          value: "12355"
        - name: GROUP_ID
          value: "pytorch-train-job6"
        - name: "WORLD_SIZE"
          value: "2"
        - name: SYNC_SERVER
          value: "http://10.101.85.29:8080/"
        - name: DATA_PATH
          value: "/app/mnt/pytorch/data/"
        - name: MODEL_PATH
          value: "/app/mnt/pytorch/models/train-job1/" 
        volumeMounts:
        - mountPath: "/app/mnt"
          name: pv-storage
        # increase share memory for docker in kubernetes
        # https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614
        # https://docs.openshift.com/container-platform/3.6/dev_guide/shared_memory.html 
        - mountPath: /dev/shm
          name: dshm